made changes to lesson 4.2
Jessica12492/R7-validations pull request #2
Opened 2023-05-11 01:09 UTC by Jessica12492

2023-05-14 06:34 UTC, dsinn requested changes
Most of this is good, but I've commented on the scenarios that don't quite work.

2023-05-14 06:34 UTC, dsinn commented on spec/models/customer_spec.rb
> +  end
"is not valid" scenarios are supposed to set an attribute to an invalid value and then verify that the subject is invalid because of that, similar to the `nil` scenarios above but with values that aren't `nil`. What you've done instead is verify various things about the valid values that were provided in the `subject` block near the top of the file.

in particular, `subject.phone.length` should be an integer, so there's no way it can equal `true` anyway, even if the model's validations aren't working.

2023-05-14 06:34 UTC, dsinn commented on spec/requests/customers_spec.rb
> +    customer.update({email: "amy@gmail.com"})
In a controller test, you're supposed to update the model with a call to the controller, which you commented out, not directly via the model's `update` method. This only tests that Rails is working, but not your controller.

This scenario also needs to check for a redirect.

2023-05-14 06:34 UTC, dsinn commented on spec/requests/customers_spec.rb
> +  end
This is a scenario for invalid data, but:

1. The data you passed looks valid to me.
2. The `reload` is commented out, so the test wouldn't know if its local `customer` object changed even if the `put` request succeeded.
3. The scenario title implies that it verifies that there's no redirect, but you didn't write a check for this.

2023-05-14 06:34 UTC, dsinn commented on spec/requests/customers_spec.rb
> +
Similar to the "put customer_path with valid data" scenario above, you need to be calling `delete` on the controller, not using the model's methods.

2023-05-17 12:41 UTC, Jessica12492 commented on spec/requests/customers_spec.rb
> +
I added the redirect. Do these work?

2023-05-19 14:59 UTC, dsinn requested changes

2023-05-19 14:59 UTC, dsinn commented on spec/requests/customers_spec.rb
> +      redirect_to customer
By itself, this doesn't do anything; there needs to be an expectation.

```suggestion
      expect(response).to redirect_to(customer)
```

2023-05-19 14:59 UTC, dsinn commented on spec/models/customer_spec.rb
> +  end
In the current state, these scenarios still don't test what needs to be tested. For example, we know that `subject.phone` is assigned the string `8889995678` (from line 3), and then in your first scenario, all you're doing is checking that what you assigned on line 3 is 10 characters long without invoking any of the model's validations.

In each of these scenarios, you need to set `subject.<attribute>` to something that's invalid and then call `expect(subject).to_not be_valid`.

2023-05-19 14:59 UTC, dsinn commented on spec/requests/customers_spec.rb
> +   expect(customer.email).to eq("amy@gmail.com")
Since this is a controller test, all of the attribute updates on the model need to be done through the controller. Otherwise, you're interfering with the test and it won't tell you whether your controller is behaving correctly.

```suggestion
    put customer_path(customer.id), params: {customer: {email:"amy@gmail.com"}}
    customer.reload
    expect(customer.email).to eq("amy@gmail.com")
```

2023-05-19 14:59 UTC, dsinn commented on spec/requests/customers_spec.rb
> +      redirect_to action:"destroy", id:1
Based on my previous comments, are you able to fix this? Let me know if you don't understand.

2023-05-20 16:28 UTC, dsinn approved these changes

2023-05-20 16:28 UTC, dsinn commented on spec/models/customer_spec.rb
> +    subject.phone = "123-456-789"
`123-456-789` is 11 characters long, so it's invalid in more than one way. 

```suggestion
    subject.phone = "123-456-78"
```

2023-05-20 17:55 UTC, merged