made changes to lesson 4.3
Jessica12492/R7-validations pull request #3
Opened 2023-05-24 15:20 UTC by Jessica12492

2023-05-26 15:51 UTC, dsinn requested changes
I know I left a lot of comments here, but the two main things I'd like to see are:

1. The first `put order_path with invalid data` scenario isn't quite right; could you fix that (see comments)?
2. I don't see the changes needed for this specification in [the assignment](https://learn.codethedream.org/rails-comprehensive-assignment/); could you point out where the code for this is or add it if it's not there?
    > 7. Change the show view for the customer, so that if that customer has orders, a list of them are shown in a table at the bottom, with show/update/delete links.  You will need to add the appropriate has_many line to the customer model. To create this table, you can follow an example: the index view from the rails5 directory R7-blog repository. Be sure you only show the orders associated with the customer, not all orders.

2023-05-26 15:51 UTC, dsinn commented on app/controllers/customers_controller.rb
> +    @customer = Customer.find(params[:id])
Isn't this already set in the `before_action`?

2023-05-26 15:51 UTC, dsinn commented on app/controllers/orders_controller.rb
> + # rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
Why is this commented?

2023-05-26 15:51 UTC, dsinn commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:id])
Like in CustomersController, isn't this already set in the `before_action`?

2023-05-26 15:51 UTC, dsinn commented on app/controllers/orders_controller.rb
> +        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
As you have in the `update` method, passing in the Order object directly also works and is less verbose.

```suggestion
        format.html { redirect_to @order, notice: "Order was successfully created." }
```

2023-05-26 15:51 UTC, dsinn commented on app/models/order.rb
> +  accepts_nested_attributes_for :customer
Where is this being used, and how?

2023-05-26 15:51 UTC, dsinn commented on app/models/order.rb
> +  validates :product_count, presence: true
I don't know why the `numericality` option is missing, but since this is a positive integer, it should have:

```suggestion
  validates :product_count, numericality: { only_integer: true, greater_than: 0 }
```

2023-05-26 15:51 UTC, dsinn commented on app/views/orders/_form.html.erb
> +    <%= form.text_field :product_count %>
```suggestion
    <%= form.number_field :product_count, in: 1..1000 %>
```

2023-05-26 15:51 UTC, dsinn commented on app/views/orders/_order.html.erb
> +    <strong>Product_Name:</strong>
`Customer Name` below doesn't have an underscore, not sure why the product fields do? The underscore would only really make sense if they're lowercase anyway since that would correspond to the attribute names.

```suggestion
    <strong>Product Name:</strong>
```

2023-05-26 15:51 UTC, dsinn commented on app/views/orders/edit.html.erb
> +<%= render partial: "form" %>
I'm actually a bit surprised if this works? Until now I've only seen the order getting passed in to the partial.

2023-05-26 15:51 UTC, dsinn commented on app/views/orders/index.html.erb
> +<div id="order_1">
One of these divs isn't closed, so you'd have layout problems if there were more to this page (e.g., a footer gets added later).

2023-05-26 15:51 UTC, dsinn commented on db/migrate/20230501140953_create_customers.rb
> +      t.references :customer_id, null: false, foreign_key: true, type: integer
It doesn't make sense to create a foreign key for the same table. If you try to roll back and re-run this migration, I'm pretty sure you'd run into an error. The customer migration already ran last week, and in general you don't want to edit a migration file that already ran, because `bin/rails db:migrate` checks for new migrations and not whether anything in old migration files changed.

2023-05-26 15:51 UTC, dsinn commented on db/migrate/20230520180121_create_orders.rb
> +      t.references :customer_id, null: false, foreign_key: true, type: integer
I'm also surprised that `customer_id` works. Normally they're done this way:

```suggestion
      t.references :customer, null: false, foreign_key: true
```

2023-05-26 15:51 UTC, dsinn commented on spec/requests/orders_spec.rb
> +  it "updates an entry and redirects to the show path for the customer" do
```suggestion
  it "updates an entry and redirects to the show path for the order" do
```

2023-05-26 15:51 UTC, dsinn commented on spec/requests/orders_spec.rb
> +    put "/orders/#{order.id}", params: {order: {product_name: 'orange'}}
I don't know why you suddenly switched from using the URL helpers to hardcoding the URLs, but in general it's better to use the helpers when you can so that you can find the references more easily, and you have less to change if the paths ever change.

```suggestion
    put order_path(id: order.id), params: {order: {product_name: 'orange'}}
```

2023-05-26 15:51 UTC, dsinn commented on spec/requests/orders_spec.rb
> +  it "does not update the customer record or redirect" do
```suggestion
  it "does not update the order record or redirect" do
```

2023-05-26 15:51 UTC, dsinn commented on spec/requests/orders_spec.rb
> +    expect(order.customer_id).not_to eq(20)
The data you pass to the controller and the expectation don't make sense here. In what case could the customer ID become 20?

2023-05-26 21:23 UTC, Jessica12492 commented on app/models/order.rb
> +  accepts_nested_attributes_for :customer
When I try to add the has_many line to the customer model table I get errors. But once I changed it to belongs to :customer. The page refresh and I was able to see the page. I'm not quite sure.

2023-06-02 04:56 UTC, dsinn commented on app/models/order.rb
> +  accepts_nested_attributes_for :customer
The `belongs_to` makes sense, but I was asking about the `accepts_nested_attributes_for`. It doesn't break anything, but it's extra functionality that doesn't need to exist.

2023-06-02 05:03 UTC, dsinn requested changes
Regarding my [previous review](https://github.com/Jessica12492/R7-validations/pull/3#pullrequestreview-1444349427), I see the attempt to fix point 1, but the test is still incorrect and I don't see where your code for point 2 is.

2023-06-02 05:03 UTC, dsinn commented on spec/requests/orders_spec.rb
> +    expect(order.product_name).not_to eq(20)
You've passed in a `product_count` into the controller, but then check `product_name`. It also doesn't look like the data is invalid?

2023-06-02 05:04 UTC, dsinn commented on spec/requests/orders_spec.rb
> +    expect(response).not_to redirect_to("orders#{order.id}")
`"orders#{order.id}"` could evaluate to `order1`, `order2`, `order3`, etc., which aren't valid paths.

2023-06-05 18:09 UTC, dsinn commented on app/views/customers/show.html.erb
> +<%= render @customer.orders %>
This page still needs to render the customer object, not just the associated orders.

```suggestion
<%= render @customer %>
```

2023-06-05 18:09 UTC, dsinn approved these changes

2023-06-05 21:13 UTC, merged